server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: liu
    password: Liu1988226
    url: jdbc:mysql://cdb-kx7bfwy2.bj.tencentcdb.com:10187/mybatis_shiro?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  profiles:
    active: classpath:logback-black.xml

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mybatis/*Mapper.xml


  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

debug: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
